//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Administration.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public class AdimManagementConstants
    {
        
        public const string AMId = "@AMId_PSY";
        
        public const string SecurityManagement = "@SecurityManagement_PSY";
        
        public const string HierarchyManagement = "@HierarchyManagement_PSY";
        
        public const string PlantManagement = "@PlantManagement_PSY";
        
        public const string UserManagement = "@UserManagement_PSY";
        
        public const string CreatedBy = "@CreatedBy_PSY";
        
        public const string CreatedDate = "@CreatedDate_PSY";
        
        public const string ModifiedBy = "@ModifiedBy_PSY";
        
        public const string ModifiedDate = "@ModifiedDate_PSY";
        
        public const string USP_AdimManagement_PSY_GET_ALL = "dbo.USP_AdimManagement_PSY_GET_ALL";
        
        public const string USP_AdimManagement_PSY_GET = "dbo.USP_AdimManagement_PSY_GET";
        
        public const string USP_AdimManagement_PSY_INSERT = "dbo.USP_AdimManagement_PSY_INSERT";
        
        public const string USP_AdimManagement_PSY_UPDATE = "dbo.USP_AdimManagement_PSY_UPDATE";
        
        public const string USP_AdimManagement_PSY_DELETE = "dbo.USP_AdimManagement_PSY_DELETE";
        
        public const string USP_AdimManagement_PSY_DELETE_ALL = "dbo.USP_AdimManagement_PSY_DELETE_ALL";
        
        public const string USP_QuickAdimManagement_INSERT = "dbo.USP_QuickAdimManagement_INSERT";
        
        public const string USP_QuickAdimManagement_UPDATE = "dbo.USP_QuickAdimManagement_UPDATE";
    }
}
