//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Administration.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public class HierarchyManagementConstants
    {
        
        public const string HMId = "@HMId_PSY";
        
        public const string AdminManagerId = "@AdminManagerId_PSY";
        
        public const string DepartmentConfiguration = "@DepartmentConfiguration_PSY";
        
        public const string RoleConfiguration = "@RoleConfiguration_PSY";
        
        public const string SetFunctionalProfile = "@SetFunctionalProfile_PSY";
        
        public const string CreatedBy = "@CreatedBy_PSY";
        
        public const string CreatedDate = "@CreatedDate_PSY";
        
        public const string ModifiedBy = "@ModifiedBy_PSY";
        
        public const string ModifiedDate = "@ModifiedDate_PSY";
        
        public const string USP_HierarchyManagement_PSY_GET_ALL = "dbo.USP_HierarchyManagement_PSY_GET_ALL";
        
        public const string USP_HierarchyManagement_PSY_GET = "dbo.USP_HierarchyManagement_PSY_GET";
        
        public const string USP_HierarchyManagement_PSY_INSERT = "dbo.USP_HierarchyManagement_PSY_INSERT";
        
        public const string USP_HierarchyManagement_PSY_UPDATE = "dbo.USP_HierarchyManagement_PSY_UPDATE";
        
        public const string USP_HierarchyManagement_PSY_DELETE = "dbo.USP_HierarchyManagement_PSY_DELETE";
        
        public const string USP_HierarchyManagement_PSY_DELETE_ALL = "dbo.USP_HierarchyManagement_PSY_DELETE_ALL";
        
        public const string USP_QuickHierarchyManagement_INSERT = "dbo.USP_QuickHierarchyManagement_INSERT";
        
        public const string USP_QuickHierarchyManagement_UPDATE = "dbo.USP_QuickHierarchyManagement_UPDATE";
    }
}
