//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Administration.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public class PlantManagementConstants
    {
        
        public const string PMId = "@PMId_PSY";
        
        public const string AdminManagerId = "@AdminManagerId_PSY";
        
        public const string PlantName = "@PlantName_PSY";
        
        public const string PlantCode = "@PlantCode_PSY";
        
        public const string PlantAddress = "@PlantAddress_PSY";
        
        public const string Comments = "@Comments_PSY";
        
        public const string CreatedBy = "@CreatedBy_PSY";
        
        public const string CreatedDate = "@CreatedDate_PSY";
        
        public const string ModifiedBy = "@ModifiedBy_PSY";

        public const string Status = "@Status_PSY";

        public const string ModifiedDate = "@ModifiedDate_PSY";
        
        public const string USP_PlantManagement_PSY_GET_ALL = "dbo.USP_PlantManagement_PSY_GET_ALL";
        
        public const string USP_PlantManagement_PSY_GET = "dbo.USP_PlantManagement_PSY_GET";
        
        public const string USP_PlantManagement_PSY_INSERT = "dbo.USP_PlantManagement_PSY_INSERT";
        
        public const string USP_PlantManagement_PSY_UPDATE = "dbo.USP_PlantManagement_PSY_UPDATE";
        
        public const string USP_PlantManagement_PSY_DELETE = "dbo.USP_PlantManagement_PSY_DELETE";
        
        public const string USP_PlantManagement_PSY_DELETE_ALL = "dbo.USP_PlantManagement_PSY_DELETE_ALL";
        
        public const string USP_QuickPlantManagement_INSERT = "dbo.USP_QuickPlantManagement_INSERT";
        
        public const string USP_QuickPlantManagement_UPDATE = "dbo.USP_QuickPlantManagement_UPDATE";
    }
}
