//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Administration.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public class SecurityManagementConstants
    {
        
        public const string SMId = "@SMId_PSY";
        
        public const string AdminManagerId = "@AdminManagerId_PSY";
        
        public const string MinimumUserIdLength = "@MinimumUserIdLength_PSY";
        
        public const string MinimumPasswordLength = "@MinimumPasswordLength_PSY";
        
        public const string PasswordComplexity = "@PasswordComplexity_PSY";
        
        public const string InvalidAttempts = "@InvalidAttempts_PSY";
        
        public const string SessionTimeOut = "@SessionTimeOut_PSY";
        
        public const string CreatedBy = "@CreatedBy_PSY";
        
        public const string CreatedDate = "@CreatedDate_PSY";
        
        public const string ModifiedBy = "@ModifiedBy_PSY";
        
        public const string ModifiedDate = "@ModifiedDate_PSY";
        
        public const string USP_SecurityManagement_PSY_GET_ALL = "dbo.USP_SecurityManagement_PSY_GET_ALL";
        
        public const string USP_SecurityManagement_PSY_GET = "dbo.USP_SecurityManagement_PSY_GET";
        
        public const string USP_SecurityManagement_PSY_INSERT = "dbo.USP_SecurityManagement_PSY_INSERT";
        
        public const string USP_SecurityManagement_PSY_UPDATE = "dbo.USP_SecurityManagement_PSY_UPDATE";
        
        public const string USP_SecurityManagement_PSY_DELETE = "dbo.USP_SecurityManagement_PSY_DELETE";
        
        public const string USP_SecurityManagement_PSY_DELETE_ALL = "dbo.USP_SecurityManagement_PSY_DELETE_ALL";
        
        public const string USP_QuickSecurityManagement_INSERT = "dbo.USP_QuickSecurityManagement_INSERT";
        
        public const string USP_QuickSecurityManagement_UPDATE = "dbo.USP_QuickSecurityManagement_UPDATE";
    }
}
