//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Administration.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public class UserConfigurationConstants
    {
        
        public const string UCFId = "@UCFId_PSY";
        
        public const string UserManagementID = "@UserManagementID_PSY";
        
        public const string FirstName = "@FirstName_PSY";
        
        public const string LastName = "@LastName_PSY";
        
        public const string UserID = "@UserID_PSY";
        
        public const string Department = "@Department_PSY";
        
        public const string Role = "@Role_PSY";
        
        public const string Doj = "@Doj_PSY";
        
        public const string Empid = "@Empid_PSY";
        
        public const string EmailId = "@EmailId_PSY";
        
        public const string Activedirectory = "@Activedirectory_PSY";
        
        public const string Standarduser = "@Standarduser_PSY";
        
        public const string CreatedBy = "@CreatedBy_PSY";
        
        public const string CreatedDate = "@CreatedDate_PSY";
        
        public const string ModifiedBy = "@ModifiedBy_PSY";

        public const string Status = "@Status_PSY";

        public const string ModifiedDate = "@ModifiedDate_PSY";
        public const string Password = "@Password_PSY";
        
        public const string USP_UserConfiguration_PSY_GET_ALL = "dbo.USP_UserConfiguration_PSY_GET_ALL";
        
        public const string USP_UserConfiguration_PSY_GET = "dbo.USP_UserConfiguration_PSY_GET";
        
        public const string USP_UserConfiguration_PSY_INSERT = "dbo.USP_UserConfiguration_PSY_INSERT";
        
        public const string USP_UserConfiguration_PSY_UPDATE = "dbo.USP_UserConfiguration_PSY_UPDATE";
        
        public const string USP_UserConfiguration_PSY_DELETE = "dbo.USP_UserConfiguration_PSY_DELETE";
        
        public const string USP_UserConfiguration_PSY_DELETE_ALL = "dbo.USP_UserConfiguration_PSY_DELETE_ALL";
        
        public const string USP_QuickUserConfiguration_INSERT = "dbo.USP_QuickUserConfiguration_INSERT";
        
        public const string USP_QuickUserConfiguration_UPDATE = "dbo.USP_QuickUserConfiguration_UPDATE";
        
        public const string UMId = "@UMId_PSY";
        
        public const string USP_UserConfiguration_PSY_By_UMId_GET = "dbo.USP_UserConfiguration_PSY_By_UMId_GET";
        
        public const string USP_UserConfiguration_PSY_By_UMId_DELETE = "dbo.USP_UserConfiguration_PSY_By_UMId_DELETE";
    }

    public class ApprovalkConfigurationConstants
    {

        public const string DocTypeNoOfApprovals = "@DocTypeNoOfApprovals";

        public const string DocTempNoOfApprovals = "@DocTempNoOfApprovals";

        public const string WFlowNoOfApprovals = "@WFlowNoOfApprovals";


        public const string USP_ApprovalConfiguration_PSY_INSERT_ALL = "dbo.USP_APPROVALcONFIGURATION_PSY_INSERT";

        public const string USP_ApprovalConfiguration_PSY_GET = "dbo.USP_GETAPPROVALCONFIG_PSY";



    }

}
