//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicySummary.DMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public class workitemsConstants
    {
        
        public const string WITId = "@WITId_PSY";
        
        public const string TaskType = "@TaskType_PSY";

        public const string TaskName = "@TaskName_PSY";

        public const string Stage = "@Stage_PSY";
        
        public const string AssignedToGroup = "@AssignedToGroup_PSY";
        
        public const string InitiatedOn = "@InitiatedOn_PSY";
        public const string InitiatedBy = "@InitiatedBy_PSY";

        public const string Status = "@Status_PSY";
        
        public const string DueDate = "@DueDate_PSY";
        
        public const string CreatedBy = "@CreatedBy_PSY";
        
        public const string CreatedDate = "@CreatedDate_PSY";
        
        public const string ModifiedBy = "@ModifiedBy_PSY";
        
        public const string ModifiedDate = "@ModifiedDate_PSY";
        public const string ReferenceId = "@RefrenceId_PSY";
        public const string ActionType = "@ActionType_PSY";
        public const string IsCompleted = "@IsCompleted_PSY";

        public const string USP_workitems_PSY_GET_ALL = "dbo.USP_workitems_PSY_GET_ALL";
        
        public const string USP_workitems_PSY_GET = "dbo.USP_workitems_PSY_GET";
        
        public const string USP_workitems_PSY_INSERT = "dbo.USP_workitems_PSY_INSERT";
        
        public const string USP_workitems_PSY_UPDATE = "dbo.USP_workitems_PSY_UPDATE";
        
        public const string USP_workitems_PSY_DELETE = "dbo.USP_workitems_PSY_DELETE";
        
        public const string USP_workitems_PSY_DELETE_ALL = "dbo.USP_workitems_PSY_DELETE_ALL";
        
        public const string USP_Quickworkitems_INSERT = "dbo.USP_Quickworkitems_INSERT";
        
        public const string USP_Quickworkitems_UPDATE = "dbo.USP_Quickworkitems_UPDATE";
    }
}
