//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Administration.DataAccess
{
    using System;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Vlims.Administration.Entities;
    using Vlims.Common;



    // Comment
    public static class DepartmentConfigurationConverter
    {
        
        public static List<DepartmentConfiguration> SetAllDepartmentConfiguration(DataSet dataset)
        {
            try
            {
                List<DepartmentConfiguration> result = new List<DepartmentConfiguration>();
                DepartmentConfiguration departmentConfigurationData;
                if (dataset != null && dataset.Tables.Count > 0 && dataset.Tables[0].Rows.Count > 0)
                {
                    for (int i = 0; (i < dataset.Tables[0].Rows.Count); i = (i + 1))
                    {
                        DataRow row = dataset.Tables[0].Rows[i];
                        departmentConfigurationData = new DepartmentConfiguration();
                        departmentConfigurationData.DPCFId = Convert.ToString(row[DepartmentConfigurationConstants.DPCFId.Trim('@')]);
                        departmentConfigurationData.HierarchyManagementId = Convert.ToString(row[DepartmentConfigurationConstants.HierarchyManagementId.Trim('@')]);
                        departmentConfigurationData.DepartmentName = Convert.ToString(row[DepartmentConfigurationConstants.DepartmentName.Trim('@')]);
                        departmentConfigurationData.DepartmentCode = Convert.ToString(row[DepartmentConfigurationConstants.DepartmentCode.Trim('@')]);
                        departmentConfigurationData.Comments = Convert.ToString(row[DepartmentConfigurationConstants.Comments.Trim('@')]);
                        departmentConfigurationData.CreatedBy = Convert.ToString(row[DepartmentConfigurationConstants.CreatedBy.Trim('@')]);
                        departmentConfigurationData.CreatedDate = DatatypeConverter.SetDateTime(row[DepartmentConfigurationConstants.CreatedDate.Trim('@'  )]);
                        departmentConfigurationData.ModifiedBy = Convert.ToString(row[DepartmentConfigurationConstants.ModifiedBy.Trim('@' )]);
                        departmentConfigurationData.ModifiedDate = DatatypeConverter.SetDateTime(row[DepartmentConfigurationConstants.ModifiedDate.Trim('@')]);
                        result.Add(departmentConfigurationData);
                    }
                }
                return result;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public static DepartmentConfiguration SetDepartmentConfiguration(DataSet dataset)
        {
            var result = SetAllDepartmentConfiguration(dataset);
            if (result.Count > 0)
            {
                return result.FirstOrDefault();
            }
            return null;
        }
        
        public static DataTable SetDataSet(List<DepartmentConfiguration> departmentConfigurations)
        {
            DataTable dataTable = new DataTable();
            DataRow row = null;
            SetDataTableColumns(dataTable);
            try
            {
                if (departmentConfigurations != null && departmentConfigurations.Count > 0)
                {
                    for (int i = 0; (i < departmentConfigurations.Count); i = (i + 1))
                    {
                        row = dataTable.NewRow();
                        row[DepartmentConfigurationConstants.DPCFId.Trim()] = departmentConfigurations[i].DPCFId;
                        row[DepartmentConfigurationConstants.HierarchyManagementId.Trim()] = departmentConfigurations[i].HierarchyManagementId;
                        row[DepartmentConfigurationConstants.DepartmentName.Trim()] = departmentConfigurations[i].DepartmentName;
                        row[DepartmentConfigurationConstants.DepartmentCode.Trim()] = departmentConfigurations[i].DepartmentCode;
                        row[DepartmentConfigurationConstants.Comments.Trim()] = departmentConfigurations[i].Comments;
                        row[DepartmentConfigurationConstants.CreatedBy.Trim()] = departmentConfigurations[i].CreatedBy;
                        row[DepartmentConfigurationConstants.CreatedDate.Trim()] = departmentConfigurations[i].CreatedDate;
                        row[DepartmentConfigurationConstants.ModifiedBy.Trim()] = departmentConfigurations[i].ModifiedBy;
                        row[DepartmentConfigurationConstants.ModifiedDate.Trim()] = departmentConfigurations[i].ModifiedDate;
                        dataTable.Rows.Add(row);
                    }
                }
                return dataTable;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        private static void SetDataTableColumns(DataTable dataTable)
        {
            dataTable.TableName = "UT_DepartmentConfiguration_PSY";
            dataTable.Columns.Add(DepartmentConfigurationConstants.DPCFId.Trim());
            dataTable.Columns.Add(DepartmentConfigurationConstants.HierarchyManagementId.Trim());
            dataTable.Columns.Add(DepartmentConfigurationConstants.DepartmentName.Trim());
            dataTable.Columns.Add(DepartmentConfigurationConstants.DepartmentCode.Trim());
            dataTable.Columns.Add(DepartmentConfigurationConstants.Comments.Trim());
            dataTable.Columns.Add(DepartmentConfigurationConstants.CreatedBy.Trim());
            dataTable.Columns.Add(DepartmentConfigurationConstants.CreatedDate.Trim());
            dataTable.Columns.Add(DepartmentConfigurationConstants.ModifiedBy.Trim());
            dataTable.Columns.Add(DepartmentConfigurationConstants.ModifiedDate.Trim());
        }
    }
}
