//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Administration.DataAccess
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Vlims.Administration.Entities;
    using Vlims.Common;



    // Comment
    public static class SecurityManagementConverter
    {
        
        public static List<SecurityManagement> SetAllSecurityManagement(DataSet dataset)
        {
            try
            {
                List<SecurityManagement> result = new List<SecurityManagement>();
                SecurityManagement securityManagementData;
                if (dataset != null && dataset.Tables.Count > 0 && dataset.Tables[0].Rows.Count > 0)
                {
                    for (int i = 0; (i < dataset.Tables[0].Rows.Count); i = (i + 1))
                    {
                        DataRow row = dataset.Tables[0].Rows[i];
                        securityManagementData = new SecurityManagement();
                        securityManagementData.SMId = Convert.ToString(row[SecurityManagementConstants.SMId.Trim('@')]);
                        securityManagementData.AdminManagerId = Convert.ToString(row[SecurityManagementConstants.AdminManagerId.Trim('@')]);
                        securityManagementData.MinimumUserIdLength = Convert.ToString(row[SecurityManagementConstants.MinimumUserIdLength.Trim('@')]);
                        securityManagementData.MinimumPasswordLength = Convert.ToString(row[SecurityManagementConstants.MinimumPasswordLength.Trim('@')]);
                        securityManagementData.PasswordComplexity = DatatypeConverter.SetIntValue(row[SecurityManagementConstants.PasswordComplexity.Trim('@')]);
                        securityManagementData.InvalidAttempts = DatatypeConverter.SetIntValue(row[SecurityManagementConstants.InvalidAttempts.Trim('@')]);
                        securityManagementData.SessionTimeOut = DatatypeConverter.SetIntValue(row[SecurityManagementConstants.SessionTimeOut.Trim('@')]);
                        securityManagementData.CreatedBy = Convert.ToString(row[SecurityManagementConstants.CreatedBy.Trim('@')]);
                        securityManagementData.CreatedDate = DatatypeConverter.SetDateTime(row[SecurityManagementConstants.CreatedDate.Trim('@')]);
                        securityManagementData.ModifiedBy = Convert.ToString(row[SecurityManagementConstants.ModifiedBy.Trim('@')]);
                        securityManagementData.ModifiedDate = DatatypeConverter.SetDateTime(row[SecurityManagementConstants.ModifiedDate.Trim('@')]);
                        result.Add(securityManagementData);
                    }
                }
                return result;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public static SecurityManagement SetSecurityManagement(DataSet dataset)
        {
            var result = SetAllSecurityManagement(dataset);
            if (result.Count > 0)
            {
                return result.FirstOrDefault();
            }
            return null;
        }
    }
}
