  CREATE PROCEDURE [dbo].[USP_workitems_PSY_DELETE] @WITId_PSY int 
 AS 
 BEGIN 
  BEGIN TRY 
 DELETE FROM [dbo].[workitems_PSY]  WHERE [WITId_PSY] IN (@WITId_PSY) 
  END TRY 
 BEGIN CATCH 
 SELECT ERROR_MESSAGE(); 
 END CATCH 
 END