  CREATE PROCEDURE [dbo].[USP_UserManagement_PSY_DELETE] @UMId_PSY int 
 AS 
 BEGIN 
  BEGIN TRY 
 DELETE FROM [dbo].[UserManagement_PSY]  WHERE [UMId_PSY] IN (@UMId_PSY) 
  END TRY 
 BEGIN CATCH 
 SELECT ERROR_MESSAGE(); 
 END CATCH 
 END