  CREATE PROCEDURE [dbo].[USP_SecurityManagement_PSY_DELETE] @SMId_PSY int 
 AS 
 BEGIN 
  BEGIN TRY 
 DELETE FROM [dbo].[SecurityManagement_PSY]  WHERE [SMId_PSY] IN (@SMId_PSY) 
  END TRY 
 BEGIN CATCH 
 SELECT ERROR_MESSAGE(); 
 END CATCH 
 END