  CREATE PROCEDURE [dbo].[USP_HierarchyManagement_PSY_DELETE] @HMId_PSY int 
 AS 
 BEGIN 
  BEGIN TRY 
 DELETE FROM [dbo].[HierarchyManagement_PSY]  WHERE [HMId_PSY] IN (@HMId_PSY) 
  END TRY 
 BEGIN CATCH 
 SELECT ERROR_MESSAGE(); 
 END CATCH 
 END