  CREATE PROCEDURE [dbo].[USP_DocumentPreparation_PSY_DELETE] @DPNID_PSY int 
 AS 
 BEGIN 
  BEGIN TRY 
 DELETE FROM [dbo].[DocumentPreparation_PSY]  WHERE [DPNID_PSY] IN (@DPNID_PSY) 
  END TRY 
 BEGIN CATCH 
 SELECT ERROR_MESSAGE(); 
 END CATCH 
 END