  CREATE PROCEDURE [dbo].[USP_AdditionalTask_PSY_DELETE] @ATID_PSY int 
 AS 
 BEGIN 
  BEGIN TRY 
 DELETE FROM [dbo].[AdditionalTask_PSY]  WHERE [ATID_PSY] IN (@ATID_PSY) 
  END TRY 
 BEGIN CATCH 
 SELECT ERROR_MESSAGE(); 
 END CATCH 
 END