  CREATE PROCEDURE [dbo].[USP_DocumentMaster_PSY_DELETE] @Dmid_PSY int 
 AS 
 BEGIN 
  BEGIN TRY 
 DELETE FROM [dbo].[DocumentMaster_PSY]  WHERE [Dmid_PSY] IN (@Dmid_PSY) 
  END TRY 
 BEGIN CATCH 
 SELECT ERROR_MESSAGE(); 
 END CATCH 
 END