//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.DocumentMaster.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public class DocumentTemplateConfigurationConstants
    {
        
        public const string DTID = "@DTID_PSY";
        
        public const string DocumentMasterId = "@DocumentMasterId_PSY";
        
        public const string Templatename = "@Templatename_PSY";
        
        public const string Uniquecode = "@Uniquecode_PSY";
        
        public const string documenttype = "@documenttype_PSY";
        public const string description = "@description_PSY";
        
        public const string header = "@header_PSY";
        
        public const string rows = "@rows_PSY";
        
        public const string columns = "@columns_PSY";
        
        public const string footer = "@footer_PSY";

        public const string footerrows = "@footer_rows_PSY";
        public const string footercolumns = "@footer_columns_PSY";
        public const string document = "@document_PSY";

        public const string CreatedBy = "@CreatedBy_PSY";
        
        public const string CreatedDate = "@CreatedDate_PSY";
        
        public const string ModifiedBy = "@ModifiedBy_PSY";
        
        public const string ModifiedDate = "@ModifiedDate_PSY";

        public const string Status = "@Status_PSY";

        public const string USP_DocumentTemplateConfiguration_PSY_GET_ALL = "dbo.USP_DocumentTemplateConfiguration_PSY_GET_ALL";
        
        public const string USP_DocumentTemplateConfiguration_PSY_GET = "dbo.USP_DocumentTemplateConfiguration_PSY_GET";
        
        public const string USP_DocumentTemplateConfiguration_PSY_INSERT = "dbo.USP_DocumentTemplateConfiguration_PSY_INSERT";
        
        public const string USP_DocumentTemplateConfiguration_PSY_UPDATE = "dbo.USP_DocumentTemplateConfiguration_PSY_UPDATE";
        
        public const string USP_DocumentTemplateConfiguration_PSY_DELETE = "dbo.USP_DocumentTemplateConfiguration_PSY_DELETE";
        
        public const string USP_DocumentTemplateConfiguration_PSY_DELETE_ALL = "dbo.USP_DocumentTemplateConfiguration_PSY_DELETE_ALL";
        
        public const string USP_QuickDocumentTemplateConfiguration_INSERT = "dbo.USP_QuickDocumentTemplateConfiguration_INSERT";
        
        public const string USP_QuickDocumentTemplateConfiguration_UPDATE = "dbo.USP_QuickDocumentTemplateConfiguration_UPDATE";
    }
}
