//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.DocumentMaster.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public class noticationconfigurationConstants
    {
        
        public const string NCId = "@NCId_PSY";
        
        public const string DocumentMasterId = "@DocumentMasterId_PSY";
        
        public const string CreatedBy = "@CreatedBy_PSY";
        
        public const string CreatedDate = "@CreatedDate_PSY";
        
        public const string ModifiedBy = "@ModifiedBy_PSY";
        
        public const string ModifiedDate = "@ModifiedDate_PSY";
        
        public const string USP_noticationconfiguration_PSY_GET_ALL = "dbo.USP_noticationconfiguration_PSY_GET_ALL";
        
        public const string USP_noticationconfiguration_PSY_GET = "dbo.USP_noticationconfiguration_PSY_GET";
        
        public const string USP_noticationconfiguration_PSY_INSERT = "dbo.USP_noticationconfiguration_PSY_INSERT";
        
        public const string USP_noticationconfiguration_PSY_UPDATE = "dbo.USP_noticationconfiguration_PSY_UPDATE";
        
        public const string USP_noticationconfiguration_PSY_DELETE = "dbo.USP_noticationconfiguration_PSY_DELETE";
        
        public const string USP_noticationconfiguration_PSY_DELETE_ALL = "dbo.USP_noticationconfiguration_PSY_DELETE_ALL";
        
        public const string USP_Quicknoticationconfiguration_INSERT = "dbo.USP_Quicknoticationconfiguration_INSERT";
        
        public const string USP_Quicknoticationconfiguration_UPDATE = "dbo.USP_Quicknoticationconfiguration_UPDATE";
    }
}
