CREATE TABLE [dbo].[SetFunctionalProfile_PSY] (
    [SFPID_PSY]                          INT            IDENTITY (1, 1) NOT NULL,
    [Role_PSY]                           BIT            NULL,
    [AdminManagement_PSY]                BIT            NULL,
    [SecurityManagement_PSY]             BIT            NULL,
    [SecurityConfigurations_PSY]         BIT            NULL,
    [EsignandAprrovalConfigurations_PSY] BIT            NULL,
    [HirearchyManagement_PSY]            BIT            NULL,
    [RoleConfiguration_PSY]              BIT            NULL,
    [DepartmentConfiguration_PSY]        BIT            NULL,
    [SetFunctionalProfile_PSY]           BIT            NULL,
    [PlantManagement_PSY]                BIT            NULL,
    [UserManagement_PSY]                 BIT            NULL,
    [UserGroupConfiguration_PSY]         BIT            NULL,
    [ActivateStatus]                     BIT            NULL,
    [AuditLog_PSY]                       BIT            NULL,
    [DocumentMaster_PSY]                 BIT            NULL,
    [DocumentTypeConfiguration_PSY]      BIT            NULL,
    [DocumentTemplateConfiguration_PSY]  BIT            NULL,
    [WorkFlowConfiguration_PSY]          BIT            NULL,
    [DashBoardConfiguration_PSY]         BIT            NULL,
    [NotificationConfiguration_PSY]      BIT            NULL,
    [DocumentRequest_PSY]                BIT            NULL,
    [DocumentPreparation_PSY]            BIT            NULL,
    [DocumentEffectiveOut_PSY]           BIT            NULL,
    [AdditionalTasks_PSY]                BIT            NULL,
    [DocumentRevision_PSY]               BIT            NULL,
    [DocumentRepository_PSY]             BIT            NULL,
    [CreatedBy_PSY]                      NVARCHAR (100) NULL,
    [CreatedDate_PSY]                    DATETIME       NULL,
    [ModifiedBy_PSY]                     NVARCHAR (100) NULL,
    [ModifiedDate_PSY]                   DATETIME       NULL,
    CONSTRAINT [PK_SetFunctionalProfile_PSY] PRIMARY KEY CLUSTERED ([SFPID_PSY] ASC)
);

