//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
using Vlims.Common;



// Comment
public static class DocumentPrintValidator
    {
        
        public static string IsValidDocumentPrint(DocumentPrint documentPrint)
        {
            try
            {
                StringBuilder validationMessages = new StringBuilder();
                ValidationHelper validationHelper = new ValidationHelper();
               // validationMessages.Append(validationHelper.NullCheckValidator(documentPrint.DRId, nameof(documentPrint.DRId)));
                //validationMessages.Append(validationHelper.LengthCheckValidator(documentPrint.DRId,50, nameof(documentPrint.DRId)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentPrint.CreatedBy,100, nameof(documentPrint.CreatedBy)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentPrint.ModifiedBy,100, nameof(documentPrint.ModifiedBy)));
                if (!String.IsNullOrEmpty(validationMessages.ToString()))
                {
                    return Convert.ToString(validationMessages.Remove(validationMessages.ToString().LastIndexOf(','),1));
                }
                else
                {
                    return Convert.ToString(validationMessages);
                }
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }

