//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.DocumentManager.DataAccess
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
   
    //using VAMLIbrary.Core.Validators;
    using Vlims.DMS.Entities;
    using Vlims.Common;


    // Comment
    public static class DocumentPreparationValidator
    {
        
        public static string IsValidDocumentPreparation(DocumentPreparation documentPreparation)
        {
            try
            {
                StringBuilder validationMessages = new StringBuilder();
                ValidationHelper validationHelper = new ValidationHelper();
                validationMessages.Append(validationHelper.NullCheckValidator(documentPreparation.DPNID, nameof(documentPreparation.DPNID)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentPreparation.DPNID,50, nameof(documentPreparation.DPNID)));
                validationMessages.Append(validationHelper.NullCheckValidator(documentPreparation.Documentmanagerid, nameof(documentPreparation.Documentmanagerid)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentPreparation.Documentmanagerid,50, nameof(documentPreparation.Documentmanagerid)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentPreparation.documenttitle,50, nameof(documentPreparation.documenttitle)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentPreparation.documentno,50, nameof(documentPreparation.documentno)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentPreparation.documenttype,50, nameof(documentPreparation.documenttype)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentPreparation.department,50, nameof(documentPreparation.department)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentPreparation.document,200, nameof(documentPreparation.document)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentPreparation.template,50, nameof(documentPreparation.template)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentPreparation.wokflow,50, nameof(documentPreparation.wokflow)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentPreparation.details,50, nameof(documentPreparation.details)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentPreparation.CreatedBy,100, nameof(documentPreparation.CreatedBy)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentPreparation.ModifiedBy,100, nameof(documentPreparation.ModifiedBy)));
                if (!String.IsNullOrEmpty(validationMessages.ToString()))
                {
                    return Convert.ToString(validationMessages.Remove(validationMessages.ToString().LastIndexOf(','),1));
                }
                else
                {
                    return Convert.ToString(validationMessages);
                }
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
