//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.DMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public class AdditionalTaskConstants
    {
        
        public const string ATID = "@ATID_PSY";

        public const string Status_PSY = "@Status_PSY";

        public const string Version = "@Version";

        public const string Documentmanagerid = "@Documentmanagerid_PSY";

        public const string DocumentEffective_ID = "@DocumentEffective_ID";


        public const string CreatedBy = "@CreatedBy_PSY";
        
        public const string CreatedDate = "@CreatedDate_PSY";
        
        public const string ModifiedBy = "@ModifiedBy_PSY";

        public const string Workflow = "@Workflow_PSY";

        public const string Department = "@Department_PSY";

        public const string Document = "@Document_PSY";

        public const string DocumentTitle = "@DocumentTitle_PSY";

        public const string documentno = "@documentno_PSY";

        public const string DocumentType = "@DocumentType_PSY";



        public const string ModifiedDate = "@ModifiedDate_PSY";

        public const string EffectiveDate = "@EffectiveDate_PSY";

        public const string reviewDate = "@reviewDate_PSY";


        public const string USP_AdditionalTask_PSY_GET_ALL = "dbo.USP_AdditionalTask_PSY_GET_ALL";
        
        public const string USP_AdditionalTask_PSY_GET = "dbo.USP_AdditionalTask_PSY_GET";
        
        public const string USP_AdditionalTask_PSY_INSERT = "dbo.USP_AdditionalTask_PSY_INSERT";
        
        public const string USP_AdditionalTask_PSY_UPDATE = "dbo.USP_AdditionalTask_PSY_UPDATE";
        
        public const string USP_AdditionalTask_PSY_DELETE = "dbo.USP_AdditionalTask_PSY_DELETE";
        
        public const string USP_AdditionalTask_PSY_DELETE_ALL = "dbo.USP_AdditionalTask_PSY_DELETE_ALL";
        
        public const string USP_QuickAdditionalTask_INSERT = "dbo.USP_QuickAdditionalTask_INSERT";
        
        public const string USP_QuickAdditionalTask_UPDATE = "dbo.USP_QuickAdditionalTask_UPDATE";
    }
}
