//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.DMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public class DocumentEffectiveConstants
    {
        
        public const string DEID = "@DEID_PSY";
        
        public const string Documentmanagerid = "@Documentmanagerid_PSY";
        
        public const string documenttitle = "@documenttitle_PSY";
        
        public const string documentno = "@documentno_PSY";
        
        public const string documenttype = "@documenttype_PSY";
        
        public const string department = "@department_PSY";
        
        public const string document = "@document_PSY";
        
        public const string EffectiveDate = "@EffectiveDate_PSY";
        
        public const string Reviewdate = "@Reviewdate_PSY";
        
        public const string CreatedBy = "@CreatedBy_PSY";
        
        public const string CreatedDate = "@CreatedDate_PSY";
        
        public const string ModifiedBy = "@ModifiedBy_PSY";
        
        public const string workId = "@workId";

        public const string Status = "@Status_PSY";
        public const string template = "@template_PSY";

        public const string ModifiedDate = "@ModifiedDate_PSY";
        
        public const string USP_DocumentEffective_PSY_GET_ALL = "dbo.USP_DocumentEffective_PSY_GET_ALL";
        
        public const string USP_DocumentEffective_PSY_GET = "dbo.USP_DocumentEffective_PSY_GET";
        
        public const string USP_DocumentEffective_PSY_INSERT = "dbo.USP_DocumentEffective_PSY_INSERT";
        
        public const string USP_DocumentEffective_PSY_UPDATE = "dbo.USP_DocumentEffective_PSY_UPDATE";

        public const string USP_DocumentEffective_PSY_APPROVE = "dbo.USP_DocumentEffective_PSY_APPROVE";

        

        public const string USP_DocumentEffective_PSY_DELETE = "dbo.USP_DocumentEffective_PSY_DELETE";
        
        public const string USP_DocumentEffective_PSY_DELETE_ALL = "dbo.USP_DocumentEffective_PSY_DELETE_ALL";
        
        public const string USP_QuickDocumentEffective_INSERT = "dbo.USP_QuickDocumentEffective_INSERT";
        
        public const string USP_QuickDocumentEffective_UPDATE = "dbo.USP_QuickDocumentEffective_UPDATE";
    }
}
