//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Administration
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;
    using Vlims.Administration.Manager;
    using Vlims.Common;
    using Vlims.Administration.Entities;



    /// <summary>
    /// Comment
    /// </summary>
    [ApiController()]
    [Route("api/adimmanagement")]
    public class AdimManagementController : ControllerBase
    {
        
        private readonly IAdimManagementService adimManagementService;
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="adimManagementService"></param>
        public AdimManagementController(IAdimManagementService adimManagementService)
        {
            this.adimManagementService = adimManagementService;
        }
        
        /// <summary>
        /// This method is used to Get List of AdimManagement
        /// </summary>
        /// <param name="requestContext"></param>
        [HttpPost()]
        public ActionResult<ResponseContext<AdimManagement>> GetAllAdimManagement(RequestContext requestContext)
        {
            var result = adimManagementService.GetAllAdimManagement(requestContext);
            return result;
        }
        
        /// <summary>
        /// This method is used to Get AdimManagement By Id aMId
        /// </summary>
        /// <param name="aMId"></param>
        [HttpGet("{aMId}")]
        public ActionResult<AdimManagement> GetAdimManagementByAMId(string aMId)
        {
            var result = adimManagementService.GetAdimManagementByAMId(aMId);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Save AdimManagement
        /// </summary>
        /// <param name="adimManagement"></param>
        [HttpPost("saveadimmanagement")]
        public ActionResult<System.Boolean> SaveAdimManagement(AdimManagement adimManagement)
        {
            var result = adimManagementService.SaveAdimManagement(adimManagement);
            return result;
        }
        
        /// <summary>
        /// This Method is used to update AdimManagement
        /// </summary>
        /// <param name="adimManagement"></param>
        [HttpPost("updateadimmanagement")]
        public ActionResult<System.Boolean> UpdateAdimManagement(AdimManagement adimManagement)
        {
            var result = adimManagementService.UpdateAdimManagement(adimManagement);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Delete AdimManagement By Id aMId
        /// </summary>
        /// <param name="aMId"></param>
        [HttpDelete("{aMId}")]
        public ActionResult<bool> DeleteAdimManagementByAMId(string aMId)
        {
            var result = adimManagementService.DeleteAdimManagementByAMId(aMId);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Delete AdimManagement By Multiple ids aMIds
        /// </summary>
        /// <param name="aMIds"></param>
        [HttpDelete("deleteAll")]
        public ActionResult<bool> DeleteAllAdimManagement(List<int> aMIds)
        {
            var result = adimManagementService.DeleteAllAdimManagement(aMIds);
            return result;
        }
    }
}
