//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.DocumentManager
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;
    using Vlims.DocumentManager.Manager;
    using Vlims.Common;
    using Vlims.DMS.Entities;


    /// <summary>
    /// Comment
    /// </summary>
    [ApiController()]
    [Route("api/documentmanager")]
    public class DocumentManagerController : ControllerBase
    {
        
        private readonly IDocumentManagerService documentManagerService;
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="documentManagerService"></param>
        public DocumentManagerController(IDocumentManagerService documentManagerService)
        {
            this.documentManagerService = documentManagerService;
        }
        
        /// <summary>
        /// This method is used to Get List of DocumentManager
        /// </summary>
        /// <param name="requestContext"></param>
        [HttpPost()]
        public ActionResult<ResponseContext<DocumentManager>> GetAllDocumentManager(RequestContext requestContext)
        {
            var result = documentManagerService.GetAllDocumentManager(requestContext);
            return result;
        }
        
        /// <summary>
        /// This method is used to Get DocumentManager By Id dMGId
        /// </summary>
        /// <param name="dMGId"></param>
        [HttpGet("{dMGId}")]
        public ActionResult<DocumentManager> GetDocumentManagerByDMGId(int dMGId)
        {
            var result = documentManagerService.GetDocumentManagerByDMGId(dMGId);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Save DocumentManager
        /// </summary>
        /// <param name="documentManager"></param>
        [HttpPost("savedocumentmanager")]
        public ActionResult<System.Boolean> SaveDocumentManager(DocumentManager documentManager)
        {
            var result = documentManagerService.SaveDocumentManager(documentManager);
            return result;
        }
        
        /// <summary>
        /// This Method is used to update DocumentManager
        /// </summary>
        /// <param name="documentManager"></param>
        [HttpPost("updatedocumentmanager")]
        public ActionResult<System.Boolean> UpdateDocumentManager(DocumentManager documentManager)
        {
            var result = documentManagerService.UpdateDocumentManager(documentManager);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Delete DocumentManager By Id dMGId
        /// </summary>
        /// <param name="dMGId"></param>
        [HttpDelete("{dMGId}")]
        public ActionResult<bool> DeleteDocumentManagerByDMGId(int dMGId)
        {
            var result = documentManagerService.DeleteDocumentManagerByDMGId(dMGId);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Delete DocumentManager By Multiple ids dMGIds
        /// </summary>
        /// <param name="dMGIds"></param>
        [HttpDelete("deleteAll")]
        public ActionResult<bool> DeleteAllDocumentManager(List<int> dMGIds)
        {
            var result = documentManagerService.DeleteAllDocumentManager(dMGIds);
            return result;
        }
    }
}
