//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.DocumentManager.Manager
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Vlims.DMS.Entities;
    using Vlims.Common;
    using Vlims.DocumentManager.DataAccess;

    //using Vlims.DMS.Entities;


    // Comment
    public class AdditionalTaskService : IAdditionalTaskService
    {
        
        
        public ResponseContext<AdditionalTask> GetAllAdditionalTask(RequestContext requestContext)
        {
            try
            {
                DataSet dataset = AdditionalTaskData.GetAllAdditionalTask(requestContext);
                List<AdditionalTask> result = AdditionalTaskConverter.SetAllAdditionalTask(dataset);
                return new ResponseContext<AdditionalTask>() { RowCount = CommonConverter.SetRowsCount(dataset), Response = result };
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public AdditionalTask GetAdditionalTaskByATID(int aTID)
        {
            try
            {
                DataSet dataset = AdditionalTaskData.GetAdditionalTaskByATID(aTID);
                AdditionalTask result = AdditionalTaskConverter.SetAdditionalTask(dataset);
                return result;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool SaveAdditionalTask(AdditionalTask additionalTask)
        {
            try
            {
                String validationMessages = AdditionalTaskValidator.IsValidAdditionalTask(additionalTask);
                if (validationMessages.Length <= 0)
                {
                    var result = AdditionalTaskData.SaveAdditionalTask(additionalTask);
                    return result;
                }
                throw new System.Exception(validationMessages);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool UpdateAdditionalTask(AdditionalTask additionalTask)
        {
            try
            {
                String validationMessages = AdditionalTaskValidator.IsValidAdditionalTask(additionalTask);
                if (validationMessages.Length <= 0)
                {
                    bool result = AdditionalTaskData.UpdateAdditionalTask(additionalTask);
                    return result;
                }
                throw new System.Exception(validationMessages);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool DeleteAdditionalTaskByATID(string aTID)
        {
            try
            {
                return AdditionalTaskData.DeleteAdditionalTaskByATID(aTID);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool DeleteAllAdditionalTask(List<int> aTIDs)
        {
            try
            {
                return AdditionalTaskData.DeleteAllAdditionalTask(aTIDs);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }

       
    }
}
