//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Administration.DataAccess
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Vlims.Administration.Entities;
    using Vlims.Common;



    // Comment
    public static class RoleConfigurationValidator
    {
        
        public static string IsValidRoleConfiguration(RoleConfiguration roleConfiguration)
        {
            try
            {
                StringBuilder validationMessages = new StringBuilder();
                ValidationHelper validationHelper = new ValidationHelper();
                //validationMessages.Append(validationHelper.LengthCheckValidator(roleConfiguration.ROCFId,50, nameof(roleConfiguration.ROCFId)));
                validationMessages.Append(validationHelper.NullCheckValidator(roleConfiguration.HierarchyManagementId, nameof(roleConfiguration.HierarchyManagementId)));
                validationMessages.Append(validationHelper.LengthCheckValidator(roleConfiguration.HierarchyManagementId,50, nameof(roleConfiguration.HierarchyManagementId)));
                validationMessages.Append(validationHelper.LengthCheckValidator(roleConfiguration.Role,50, nameof(roleConfiguration.Role)));
                validationMessages.Append(validationHelper.LengthCheckValidator(roleConfiguration.Department,50, nameof(roleConfiguration.Department)));
                validationMessages.Append(validationHelper.LengthCheckValidator(roleConfiguration.Comments,50, nameof(roleConfiguration.Comments)));
                validationMessages.Append(validationHelper.LengthCheckValidator(roleConfiguration.CreatedBy,100, nameof(roleConfiguration.CreatedBy)));
                validationMessages.Append(validationHelper.LengthCheckValidator(roleConfiguration.ModifiedBy,100, nameof(roleConfiguration.ModifiedBy)));
                if (!String.IsNullOrEmpty(validationMessages.ToString()))
                {
                    return Convert.ToString(validationMessages.Remove(validationMessages.ToString().LastIndexOf(','),1));
                }
                else
                {
                    return Convert.ToString(validationMessages);
                }
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
