//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicySummary.DMS.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using PolicySummary.DMS.Entities;
    using Vlims.Common;
    using Vlims.DMS.Entities;


    // Comment
    public static class workitemsValidator
    {
        
        public static string IsValidworkitems(workitems workitems)
        {
            try
            {
                StringBuilder validationMessages = new StringBuilder();
                ValidationHelper validationHelper = new ValidationHelper();
                validationMessages.Append(validationHelper.LengthCheckValidator(workitems.TaskType,50, nameof(workitems.TaskType)));
                validationMessages.Append(validationHelper.LengthCheckValidator(workitems.Stage,50, nameof(workitems.Stage)));
                validationMessages.Append(validationHelper.LengthCheckValidator(workitems.AssignedToGroup,50, nameof(workitems.AssignedToGroup)));
                validationMessages.Append(validationHelper.LengthCheckValidator(workitems.InitiatedOn,50, nameof(workitems.InitiatedOn)));
                validationMessages.Append(validationHelper.LengthCheckValidator(workitems.Status,50, nameof(workitems.Status)));
                validationMessages.Append(validationHelper.LengthCheckValidator(workitems.DueDate,50, nameof(workitems.DueDate)));
                validationMessages.Append(validationHelper.LengthCheckValidator(workitems.CreatedBy,100, nameof(workitems.CreatedBy)));
                validationMessages.Append(validationHelper.LengthCheckValidator(workitems.ModifiedBy,100, nameof(workitems.ModifiedBy)));
                if (!String.IsNullOrEmpty(validationMessages.ToString()))
                {
                    return Convert.ToString(validationMessages.Remove(validationMessages.ToString().LastIndexOf(','),1));
                }
                else
                {
                    return Convert.ToString(validationMessages);
                }
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
