//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Vlims.Common;
    using Vlims.DMS.Entities;
using PolicySummary.DMS.Services;



// Comment
public class workitemsService : IworkitemsService
    {
        
        
   
        
        public ResponseContext<workitems> GetAllworkitems(RequestContext requestContext)
        {
            try
            {
                DataSet dataset = workitemsData.GetAllworkitems(requestContext);
                List<workitems> result = workitemsConverter.SetAllworkitems(dataset);
                return new ResponseContext<workitems>() { RowCount = CommonConverter.SetRowsCount(dataset), Response = result };
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public workitems GetworkitemsByWITId(System.Int32? wITId)
        {
            try
            {
                DataSet dataset = workitemsData.GetworkitemsByWITId(wITId);
                workitems result = workitemsConverter.Setworkitems(dataset);
                return result;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool Saveworkitems(workitems workitems)
        {
            try
            {
                String validationMessages = workitemsValidator.IsValidworkitems(workitems);
                if (validationMessages.Length <= 0)
                {
                    var result = workitemsData.Saveworkitems(workitems);
                    return result;
                }
                throw new System.Exception(validationMessages);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool Updateworkitems(workitems workitems)
        {
            try
            {
                String validationMessages = workitemsValidator.IsValidworkitems(workitems);
                if (validationMessages.Length <= 0)
                {
                    bool result = workitemsData.Updateworkitems(workitems);
                    return result;
                }
                throw new System.Exception(validationMessages);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool DeleteworkitemsByWITId(System.Int32? wITId)
        {
            try
            {
                return workitemsData.DeleteworkitemsByWITId(wITId);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool DeleteAllworkitems(List<int> wITIds)
        {
            try
            {
                return workitemsData.DeleteAllworkitems(wITIds);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }

