//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.DocumentManager.Manager
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Vlims.DMS.Entities;
    using Vlims.Common;

    //using PolicySummary.DMS.Entities;


    // Comment
    public interface IAdditionalTaskService
    {
        
        ResponseContext<AdditionalTask> GetAllAdditionalTask(RequestContext requestContext);
        
        AdditionalTask GetAdditionalTaskByATID(int aTID);
        
        bool SaveAdditionalTask(AdditionalTask additionalTask);
        
        bool UpdateAdditionalTask(AdditionalTask additionalTask);
        
        bool DeleteAdditionalTaskByATID(string aTID);
        
        bool DeleteAllAdditionalTask(List<int> aTIDs);
    }
}
