//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.IO;
using System.Linq;
using System.Data;
using System.Collections.Generic;
using Vlims.Common;
using Vlims.DMS.Entities;


// Comment
public interface IworkitemsService
{

    ResponseContext<workitems> GetAllworkitems(RequestContext requestContext);

    workitems GetworkitemsByWITId(System.Int32? wITId);

    bool Saveworkitems(workitems workitems);

    bool Updateworkitems(workitems workitems);

    bool DeleteworkitemsByWITId(System.Int32? wITId);

    bool DeleteAllworkitems(List<int> wITIds);
}

