//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.DocumentMaster.Entities
{
    using System;
    using Vlims.Administration.Entities;



    // Comment
    public class workflowconiguration
    {

        private string wfcidField;

        private string documentmasteridField;

        private string documentstageField;

        private string documenttypeField;

        private string departmentField;

        private System.Int32? reviewscountField;

        private System.Int32? approvalscountField;

        private string createdbyField;

        private DateTime? createddateField;

        private string modifiedbyField;

        private DateTime? modifieddateField;

        private string statusField;
        public string WFCId
        {
            get
            {
                return this.wfcidField;
            }
            set
            {
                this.wfcidField = value;
            }
        }

        public string DocumentMasterId
        {
            get
            {
                return this.documentmasteridField;
            }
            set
            {
                this.documentmasteridField = value;
            }
        }
        public string workflowName { get; set; }
        //public string departments { get; set; }
        public string code { get; set; }
        public string documentstage
        {
            get
            {
                return this.documentstageField;
            }
            set
            {
                this.documentstageField = value;
            }
        }

        public string documenttype
        {
            get
            {
                return this.documenttypeField;
            }
            set
            {
                this.documenttypeField = value;
            }
        }




        public System.Int32? reviewsCount
        {
            get
            {
                return this.reviewscountField;
            }
            set
            {
                this.reviewscountField = value;
            }
        }

        public System.Int32? approvalsCount
        {
            get
            {
                return this.approvalscountField;
            }
            set
            {
                this.approvalscountField = value;
            }
        }
        public string reviewsType { get; set; }
        public string approvalsType { get; set; }
        public List<UserConfiguration> approvals { get; set; }
        public List<UserConfiguration> reviewers { get; set; }
        public string  reviewersGroup { get; set; }
        public string  approvalsGroup { get; set; }
        public List<DepartmentConfiguration> department { get; set; }
        public string departments { get; set; }
        public string CreatedBy
        {
            get
            {
                return this.createdbyField;
            }
            set
            {
                this.createdbyField = value;
            }
        }

        public DateTime? CreatedDate
        {
            get
            {
                return this.createddateField;
            }
            set
            {
                this.createddateField = value;
            }
        }

        public string ModifiedBy
        {
            get
            {
                return this.modifiedbyField;
            }
            set
            {
                this.modifiedbyField = value;
            }
        }
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        public DateTime? ModifiedDate
        {
            get
            {
                return this.modifieddateField;
            }
            set
            {
                this.modifieddateField = value;
            }
        }
    }
    public class WorkFlowMapping
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public int WorkFlowId { get; set; }
        public string WorkFlowName { get; set; }
        public string Type { get; set; }
    }
}
