//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Administration.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    // Comment
    public class AdimManagement
    {
        
        private string amidField;
        
        private string securitymanagementField;
        
        private string hierarchymanagementField;
        
        private string plantmanagementField;
        
        private string usermanagementField;
        
        private string createdbyField;
        
        private DateTime? createddateField;
        
        private string modifiedbyField;
        
        private DateTime? modifieddateField;
        
        public string AMId
        {
            get
            {
                return this.amidField;
            }
            set
            {
                this.amidField = value;
            }
        }
        
        public string SecurityManagement
        {
            get
            {
                return this.securitymanagementField;
            }
            set
            {
                this.securitymanagementField = value;
            }
        }
        
        public string HierarchyManagement
        {
            get
            {
                return this.hierarchymanagementField;
            }
            set
            {
                this.hierarchymanagementField = value;
            }
        }
        
        public string PlantManagement
        {
            get
            {
                return this.plantmanagementField;
            }
            set
            {
                this.plantmanagementField = value;
            }
        }
        
        public string UserManagement
        {
            get
            {
                return this.usermanagementField;
            }
            set
            {
                this.usermanagementField = value;
            }
        }
        
        public string CreatedBy
        {
            get
            {
                return this.createdbyField;
            }
            set
            {
                this.createdbyField = value;
            }
        }
        
        public DateTime? CreatedDate
        {
            get
            {
                return this.createddateField;
            }
            set
            {
                this.createddateField = value;
            }
        }
        
        public string ModifiedBy
        {
            get
            {
                return this.modifiedbyField;
            }
            set
            {
                this.modifiedbyField = value;
            }
        }
        
        public DateTime? ModifiedDate
        {
            get
            {
                return this.modifieddateField;
            }
            set
            {
                this.modifieddateField = value;
            }
        }
    }
}
