//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Administration.Entities
{
    using System;
    using System.Collections.Generic;    
    
    // Comment
    public class DepartmentConfiguration
    {
        
        private string dpcfidField;
        
        private string hierarchymanagementidField;
        
        private string departmentnameField;
        
        private string departmentcodeField;
        
        private string commentsField;
        
        private string createdbyField;
        
        private DateTime? createddateField;
        
        private string modifiedbyField;
        
        private DateTime? modifieddateField;
        
        public string DPCFId
        {
            get
            {
                return this.dpcfidField;
            }
            set
            {
                this.dpcfidField = value;
            }
        }
        
        public string HierarchyManagementId
        {
            get
            {
                return this.hierarchymanagementidField;
            }
            set
            {
                this.hierarchymanagementidField = value;
            }
        }
        
        public string DepartmentName
        {
            get
            {
                return this.departmentnameField;
            }
            set
            {
                this.departmentnameField = value;
            }
        }
        
        public string DepartmentCode
        {
            get
            {
                return this.departmentcodeField;
            }
            set
            {
                this.departmentcodeField = value;
            }
        }
        
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
        
        public string CreatedBy
        {
            get
            {
                return this.createdbyField;
            }
            set
            {
                this.createdbyField = value;
            }
        }
        
        public DateTime? CreatedDate
        {
            get
            {
                return this.createddateField;
            }
            set
            {
                this.createddateField = value;
            }
        }
        
        public string ModifiedBy
        {
            get
            {
                return this.modifiedbyField;
            }
            set
            {
                this.modifiedbyField = value;
            }
        }
        
        public DateTime? ModifiedDate
        {
            get
            {
                return this.modifieddateField;
            }
            set
            {
                this.modifieddateField = value;
            }
        }
    }
}
