//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Administration.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    // Comment
    public class HierarchyManagement
    {
        
        private string hmidField;
        
        private string adminmanageridField;
        
        private string departmentconfigurationField;
        
        private string roleconfigurationField;
        
        private string setfunctionalprofileField;
        
        private string createdbyField;
        
        private DateTime? createddateField;
        
        private string modifiedbyField;
        
        private DateTime? modifieddateField;
        
        public string HMId
        {
            get
            {
                return this.hmidField;
            }
            set
            {
                this.hmidField = value;
            }
        }
        
        public string AdminManagerId
        {
            get
            {
                return this.adminmanageridField;
            }
            set
            {
                this.adminmanageridField = value;
            }
        }
        
        public string DepartmentConfiguration
        {
            get
            {
                return this.departmentconfigurationField;
            }
            set
            {
                this.departmentconfigurationField = value;
            }
        }
        
        public string RoleConfiguration
        {
            get
            {
                return this.roleconfigurationField;
            }
            set
            {
                this.roleconfigurationField = value;
            }
        }
        
        public string SetFunctionalProfile
        {
            get
            {
                return this.setfunctionalprofileField;
            }
            set
            {
                this.setfunctionalprofileField = value;
            }
        }
        
        public string CreatedBy
        {
            get
            {
                return this.createdbyField;
            }
            set
            {
                this.createdbyField = value;
            }
        }
        
        public DateTime? CreatedDate
        {
            get
            {
                return this.createddateField;
            }
            set
            {
                this.createddateField = value;
            }
        }
        
        public string ModifiedBy
        {
            get
            {
                return this.modifiedbyField;
            }
            set
            {
                this.modifiedbyField = value;
            }
        }
        
        public DateTime? ModifiedDate
        {
            get
            {
                return this.modifieddateField;
            }
            set
            {
                this.modifieddateField = value;
            }
        }
    }
}
