//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Administration.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    // Comment
    public class PlantManagement
    {
        
        private int pmidField;
        
        private string adminmanageridField;
        
        private string plantnameField;
        
        private string plantcodeField;
        
        private string plantaddressField;
        
        private string commentsField;
        
        private string createdbyField;
        
        private DateTime? createddateField;
        
        private string modifiedbyField;
        
        private DateTime? modifieddateField;

        private string statusField;
        
        public int PMId
        {
            get
            {
                return this.pmidField;
            }
            set
            {
                this.pmidField = value;
            }
        }
        
        public string AdminManagerId
        {
            get
            {
                return this.adminmanageridField;
            }
            set
            {
                this.adminmanageridField = value;
            }
        }
        
        public string PlantName
        {
            get
            {
                return this.plantnameField;
            }
            set
            {
                this.plantnameField = value;
            }
        }
        
        public string PlantCode
        {
            get
            {
                return this.plantcodeField;
            }
            set
            {
                this.plantcodeField = value;
            }
        }
        
        public string PlantAddress
        {
            get
            {
                return this.plantaddressField;
            }
            set
            {
                this.plantaddressField = value;
            }
        }
        
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
        
        public string CreatedBy
        {
            get
            {
                return this.createdbyField;
            }
            set
            {
                this.createdbyField = value;
            }
        }
        
        public DateTime? CreatedDate
        {
            get
            {
                return this.createddateField;
            }
            set
            {
                this.createddateField = value;
            }
        }
        
        public string ModifiedBy
        {
            get
            {
                return this.modifiedbyField;
            }
            set
            {
                this.modifiedbyField = value;
            }
        }
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        public DateTime? ModifiedDate
        {
            get
            {
                return this.modifieddateField;
            }
            set
            {
                this.modifieddateField = value;
            }
        }
    }
}
