//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Administration.Entities
{
    using System;
    using System.Collections.Generic;
  //  using PolicySummary.Common.Entities;
    
    
    // Comment
    public class UserGroupConfiguration
    {
        
        private string ugcidField;
        
        private string usermanagementidField;
        
        private string usergroupnameField;
        
        private string codeField;
        
        private string usersField;
        
        private string totalusersField;
        
        private string createdbyField;
        
        private DateTime? createddateField;
        
        private string modifiedbyField;
        
        private DateTime? modifieddateField;

        private string statusField;
        public string Ugcid
        {
            get
            {
                return this.ugcidField;
            }
            set
            {
                this.ugcidField = value;
            }
        }
        
        public string Usermanagementid
        {
            get
            {
                return this.usermanagementidField;
            }
            set
            {
                this.usermanagementidField = value;
            }
        }
        
        public string usergroupname
        {
            get
            {
                return this.usergroupnameField;
            }
            set
            {
                this.usergroupnameField = value;
            }
        }
        
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        public List<UserConfiguration> users { get; set; }
        public string userstring { get; set; }
        //public string users
        //{
        //    get
        //    {
        //        return this.usersField;
        //    }
        //    set
        //    {
        //        this.usersField = value;
        //    }
        //}

        public string totalusers
        {
            get
            {
                return this.totalusersField;
            }
            set
            {
                this.totalusersField = value;
            }
        }
        
        public string createdBy
        {
            get
            {
                return this.createdbyField;
            }
            set
            {
                this.createdbyField = value;
            }
        }
        
        public DateTime? createdDate
        {
            get
            {
                return this.createddateField;
            }
            set
            {
                this.createddateField = value;
            }
        }
        
        public string modifiedBy
        {
            get
            {
                return this.modifiedbyField;
            }
            set
            {
                this.modifiedbyField = value;
            }
        }

        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        public DateTime? modifiedDate
        {
            get
            {
                return this.modifieddateField;
            }
            set
            {
                this.modifieddateField = value;
            }
        }
    }
}
