//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.DMS.Entities
{
    using System;
    using System.Collections.Generic;
    //using PolicySummary.Common.Entities;
    
    
    // Comment
    public class DocumentEffective
    {
        
        private string deidField;
        
        private string documentmanageridField;
        
        private string documenttitleField;
        
        private string documentnoField;
        
        private string documenttypeField;
        
        private string departmentField;
        
        private string documentField;
        
        private DateTime? effectivedateField;
        
        private DateTime? reviewdateField;
        
        private string createdbyField;
        
        private DateTime? createddateField;
        
        private string modifiedbyField;
        
        private DateTime? modifieddateField;

        private string statusField;

        private int workIdField;
        
        public string DEID
        {
            get
            {
                return this.deidField;
            }
            set
            {
                this.deidField = value;
            }
        }
        
        public string Documentmanagerid
        {
            get
            {
                return this.documentmanageridField;
            }
            set
            {
                this.documentmanageridField = value;
            }
        }
        
        public string documenttitle
        {
            get
            {
                return this.documenttitleField;
            }
            set
            {
                this.documenttitleField = value;
            }
        }
        
        public string documentno
        {
            get
            {
                return this.documentnoField;
            }
            set
            {
                this.documentnoField = value;
            }
        }
        
        public string documenttype
        {
            get
            {
                return this.documenttypeField;
            }
            set
            {
                this.documenttypeField = value;
            }
        }
        
        public string Department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }
        public string template { get; set; }
        public string document
        {
            get
            {
                return this.documentField;
            }
            set
            {
                this.documentField = value;
            }
        }

        //public DateTime? EffectiveDate
        //{
        //    get
        //    {
        //        return this.effectivedateField;
        //    }
        //    set
        //    {
        //        this.effectivedateField = value;
        //    }
        //}
        public string EffectiveDate { get; set; }
        public string ReviewDate { get; set; }

        //public DateTime? ReviewDate
        //{
        //    get
        //    {
        //        return this.reviewdateField;
        //    }
        //    set
        //    {
        //        this.reviewdateField = value;
        //    }
        //}
        
        public string CreatedBy
        {
            get
            {
                return this.createdbyField;
            }
            set
            {
                this.createdbyField = value;
            }
        }
        
        public DateTime? CreatedDate
        {
            get
            {
                return this.createddateField;
            }
            set
            {
                this.createddateField = value;
            }
        }
        
        public string ModifiedBy
        {
            get
            {
                return this.modifiedbyField;
            }
            set
            {
                this.modifiedbyField = value;
            }
        }
        
        public DateTime? ModifiedDate
        {
            get
            {
                return this.modifieddateField;
            }
            set
            {
                this.modifieddateField = value;
            }
        }
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        public int workId
        {
            get
            {
                return this.workIdField;
            }
            set
            {
                this.workIdField = value;
            }
        }
    }
}
