//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.DMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    // Comment
    public class DocumentManager
    {
        
        private string dmgidField;
        
        private string documentrequestField;
        
        private string documentpreparationField;
        
        private string documenteffectiveField;
        
        private string additionaltasksField;
        
        private string createdbyField;
        
        private DateTime? createddateField;
        
        private string modifiedbyField;
        
        private DateTime? modifieddateField;
        
        public string DMGId
        {
            get
            {
                return this.dmgidField;
            }
            set
            {
                this.dmgidField = value;
            }
        }
        
        public string Documentrequest
        {
            get
            {
                return this.documentrequestField;
            }
            set
            {
                this.documentrequestField = value;
            }
        }
        
        public string documentpreparation
        {
            get
            {
                return this.documentpreparationField;
            }
            set
            {
                this.documentpreparationField = value;
            }
        }
        
        public string DocumentEffective
        {
            get
            {
                return this.documenteffectiveField;
            }
            set
            {
                this.documenteffectiveField = value;
            }
        }
        
        public string AdditionalTasks
        {
            get
            {
                return this.additionaltasksField;
            }
            set
            {
                this.additionaltasksField = value;
            }
        }
        
        public string CreatedBy
        {
            get
            {
                return this.createdbyField;
            }
            set
            {
                this.createdbyField = value;
            }
        }
        
        public DateTime? CreatedDate
        {
            get
            {
                return this.createddateField;
            }
            set
            {
                this.createddateField = value;
            }
        }
        
        public string ModifiedBy
        {
            get
            {
                return this.modifiedbyField;
            }
            set
            {
                this.modifiedbyField = value;
            }
        }
        
        public DateTime? ModifiedDate
        {
            get
            {
                return this.modifieddateField;
            }
            set
            {
                this.modifieddateField = value;
            }
        }
    }
}
