//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


// Comment
public class AdditionalTask
{

    private string dridField;

    private string documentmanageridField;

    private string requestcodeField;

    private string documenttitleField;

    private string documentnoField;

    private string documenttypeField;

    private string departmentField;

    private string documentField;

    private DateTime effectivedateField;

    private DateTime reviewdateField;

    private string statusField;

    private string versionField;

    private string createdbyField;

    private DateTime? createddateField;

    private string modifiedbyField;

    private DateTime? modifieddateField;


    public string DRId
    {
        get
        {
            return this.dridField;
        }
        set
        {
            this.dridField = value;
        }
    }

    public string Documentmanagerid
    {
        get
        {
            return this.documentmanageridField;
        }
        set
        {
            this.documentmanageridField = value;
        }
    }

    public string requestcode
    {
        get
        {
            return this.requestcodeField;
        }
        set
        {
            this.requestcodeField = value;
        }
    }

    public string documenttitle
    {
        get
        {
            return this.documenttitleField;
        }
        set
        {
            this.documenttitleField = value;
        }
    }

    public string documentno
    {
        get
        {
            return this.documentnoField;
        }
        set
        {
            this.documentnoField = value;
        }
    }

    public string documenttype
    {
        get
        {
            return this.documenttypeField;
        }
        set
        {
            this.documenttypeField = value;
        }
    }

    public string department
    {
        get
        {
            return this.departmentField;
        }
        set
        {
            this.departmentField = value;
        }
    }

    public string document
    {
        get
        {
            return this.documentField;
        }
        set
        {
            this.documentField = value;
        }
    }

    public DateTime EffectiveDate
    {
        get
        {
            return this.effectivedateField;
        }
        set
        {
            this.effectivedateField = value;
        }
    }

    public DateTime Reviewdate
    {
        get
        {
            return this.reviewdateField;
        }
        set
        {
            this.reviewdateField = value;
        }
    }

    public string Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    public string Version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }

    public string CreatedBy
    {
        get
        {
            return this.createdbyField;
        }
        set
        {
            this.createdbyField = value;
        }
    }

    public DateTime? CreatedDate
    {
        get
        {
            return this.createddateField;
        }
        set
        {
            this.createddateField = value;
        }
    }

    public string ModifiedBy
    {
        get
        {
            return this.modifiedbyField;
        }
        set
        {
            this.modifiedbyField = value;
        }
    }

    public DateTime? ModifiedDate
    {
        get
        {
            return this.modifieddateField;
        }
        set
        {
            this.modifieddateField = value;
        }
    }
}

