//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.DocumentMaster.Manager
{

    using System.Collections.Generic;
    using Vlims.DocumentMaster.Entities;
    using Vlims.Common;
    




    // Comment
    public interface IDocumentTypeConfigurationService
    {
        
        ResponseContext<DocumentTypeConfiguration> GetAllDocumentTypeConfiguration(RequestContext requestContext);
        
        DocumentTypeConfiguration GetDocumentTypeConfigurationByDTCId(int dTCId);
        
        bool SaveDocumentTypeConfiguration(DocumentTypeConfiguration documentTypeConfiguration);
        
        bool UpdateDocumentTypeConfiguration(DocumentTypeConfiguration documentTypeConfiguration);
        
        bool DeleteDocumentTypeConfigurationByDTCId(int dTCId);
        
        bool DeleteAllDocumentTypeConfiguration(List<int> dTCIds);
    }
}
