//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.DocumentMaster.Manager
{
    using System.Collections.Generic;
    using Vlims.Common;
    using Vlims.DocumentMaster.Entities;



    // Comment
    public interface IworkitemsAssignedService
    {        
        ResponseContext<workflowconiguration> GetAllworkitems(RequestContext requestContext);      
       
    }
}
